/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantdb;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YAĞMUR
 */
public class Language extends javax.swing.JFrame {

    /**
     * Creates new form Language
     */
    public Language() {
        initComponents();
        Show_R_Waiter_Lang();
    }
    
    public ArrayList<R_Waiter_Lang> R_Waiter_LangList(){
    
    ArrayList <R_Waiter_Lang> R_Waiter_Lang= new ArrayList <>();
        
   
    try{
        
        Class.forName("com.mysql.jdbc.Driver");
        String url= "jdbc:sqlserver://localhost:3306/mysql?server=UTC";
        Connection conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurantdbase?zeroDateTimeBehavior=convertToNull","root","1234567");
        String query="select * from relationlangwaiter";
        
        
        Statement st= (Statement) conn.createStatement();
        ResultSet rs= st.executeQuery(query);
        R_Waiter_Lang r_Waiter_Lang;
        while(rs.next()){
            r_Waiter_Lang = new R_Waiter_Lang (rs.getInt("RelationLangWaiterID"),rs.getInt("WaiterID"),rs.getInt("LanguageID"));
            R_Waiter_Lang.add(r_Waiter_Lang);
            
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    return R_Waiter_Lang;
}
//display table

public void Show_R_Waiter_Lang(){
    ArrayList<R_Waiter_Lang>list = R_Waiter_LangList();
    DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
    Object []row= new Object [3];
    
    for(int i=0;i<list.size();i++){
        
        row[0]=list.get(i).getRelationLangWaiterID();
        row[1]=list.get(i).getWaiterID();
        row[2]=list.get(i).getLanguageID();
        
        
        model.addRow(row);
    }
    
  
    
}
 public void Add_R_Waiter_Lang(){
    ArrayList<R_Waiter_Lang>list = R_Waiter_LangList();
    DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
    Object []row= new Object [3];
    
    int i= list.size()-1;
    
        row[0]=list.get(i).getRelationLangWaiterID();
        row[1]=list.get(i).getWaiterID();
        row[2]=list.get(i).getLanguageID();
        
        
        model.addRow(row);
    
 }
 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RelationLangWaiterID", "WaiterID", "LanguageID"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Choose Languages");

        jRadioButton1.setText("English");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("German");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Spanish");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter WaiterID");

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
       Class.forName("com.mysql.jdbc.Driver");
        
        Connection conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurantdbase?zeroDateTimeBehavior=convertToNull","root","1234567");
        String query=" INSERT INTO RelationLangWaiter(WaiterID,LanguageID) VALUES (?,?);";
        
        
        PreparedStatement pst=conn.prepareStatement(query);
        
        pst.setString(1,jTextField1.getText());
        String english= "1";
        pst.setString(2,english);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "inserted successfully");
        Add_R_Waiter_Lang();
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        try{
       Class.forName("com.mysql.jdbc.Driver");
        
        Connection conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurantdbase?zeroDateTimeBehavior=convertToNull","root","1234567");
        String query=" INSERT INTO RelationLangWaiter(WaiterID,LanguageID) VALUES (?,?);";
        
        
        PreparedStatement pst=conn.prepareStatement(query);
        
        pst.setString(1,jTextField1.getText());
        String german= "2";
        pst.setString(2,german);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "inserted successfully");
        Add_R_Waiter_Lang();
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        try{
       Class.forName("com.mysql.jdbc.Driver");
        
        Connection conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurantdbase?zeroDateTimeBehavior=convertToNull","root","1234567");
        String query=" INSERT INTO RelationLangWaiter(WaiterID,LanguageID) VALUES (?,?);";
        
        
        PreparedStatement pst=conn.prepareStatement(query);
        
        pst.setString(1,jTextField1.getText());
        String spanish= "3";
        pst.setString(2,spanish);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "inserted successfully");
        Add_R_Waiter_Lang();
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        waiterinfo t= new waiterinfo();
        t.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Language.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Language().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
